{
    'name': 'Hospital',
    'application': True,
    'data': [
        'security/ir.model.access.csv',
        'views/hospital_patient_views.xml',
        'views/hospital_patient_menus.xml',
        'views/hospital_doctor_views.xml',
        'views/hospital_doctor_menus.xml',
        'views/hospital_diagnosis_views.xml',
        'views/hospital_diagnosis_menus.xml',
        'views/hospital_contact_views.xml',
        'views/hospital_illness_views.xml',
        'views/hospital_illness_menus.xml',
        'views/hospital_illness_type_views.xml',
        'views/hospital_visit_views.xml',
        'views/hospital_visit_menus.xml',
        'views/hospital_doctor_history_views.xml',
        'views/hospital_doctor_history_menus.xml',
        'views/hospital_research_views.xml',
        'views/hospital_research_menus.xml',
        'views/hospital_research_type_views.xml',
        'views/hospital_research_type_menus.xml',
        'views/hospital_sample_type_views.xml',
        'views/hospital_sample_type_menus.xml',
        'views/hospital_doctor_schedule_views.xml',
        'views/hospital_doctor_schedule_menus.xml',
        'wizard/hospital_reassign_doctor_views.xml',
        'wizard/hospital_reassign_doctor_menus.xml',
        'wizard/hospital_reschedule_appointment_views.xml',
        'wizard/hospital_reschedule_appointment_menus.xml',
        'wizard/hospital_doctor_weekly_schedule_views.xml',
        'wizard/hospital_doctor_weekly_schedule_menus.xml',
        'wizard/hospital_disease_report_views.xml',
        'wizard/hospital_disease_report_menus.xml',
        'wizard/disease_report_views.xml',
        'wizard/disease_report_menus.xml'

    ],
}
